name: interfaces
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5
  http: ^1.1.0
  cupertino_icons: ^1.0.8
  # Remove google_fonts for now to avoid version issues
  # google_fonts: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
 

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Italic.ttf
  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/images/fonts/Poppins-Regular.ttf
  #       - asset: assets/images/fonts/Poppins-Bold.ttf